tanhakabir/SwiftAudioPlayer

Example/SwiftAudioPlayer/Base.lproj/Main.storyboard, Example/SwiftAudioPlayer/ViewController.swift
so I fix when seek the song, previously when move the seek bar forward or backward always end up back to the zero position
=> fix seek bar on player

Example/SwiftAudioPlayer/Info.plist, Source/LockScreenViewProtocol.swift, Source/SAPlayer.swift, Source/SAPlayerPresenter.swift
fixing AVAudioSession configuration when playing a song or audio on background
fix setup mini player on lockscreen.
Thank you
=> Fix miniplayer onbackground

Example/SwiftAudioPlayer/ViewController.swift, Source/Engine/AudioThrottler.swift, Source/Engine/Parser/AudioParser.swift, Source/Model/Streaming/AudioStreamWorker.swift, Source/SAPlayer.swift, Source/SAPlayerUpdateSubscription.swift
=> Fix live streams/servers with unpredictable size at beginning of stream being playable

Example/SwiftAudioPlayer/ViewController.swift
=> fix crash on cancel streaming pressed

Example/SwiftAudioPlayer/ViewController.swift, Source/Engine/AudioDiskEngine.swift, Source/Engine/AudioStreamEngine.swift, Source/Model/Streaming/AudioStreamWorker.swift, Source/SAPlayer.swift, Source/SAPlayerDelegate.swift, Source/SAPlayerPresenter.swift
=> implement streaming cancellation

Source/Engine/Parser/AudioParserPacketListener.swift
I added one IF to check the swift version and still works in older versions
=> Fixed bug in swift 5.3

README.md
=> Update README to include module name for import

Source/SAPlayer.swift
=> Open up access to playerNode in API

Example/SwiftAudioPlayer/ViewController.swift, README.md, Source/Model/AudioDataManager.swift, Source/SAPlayerDownloader.swift
close #35
Fixes simulators not downloading because of cellular download preference being set to false.
=> create API for setting preference for downloading on cellular data

Source/Engine/AudioStreamEngine.swift
Co-Authored-By: @nt4f04uNd
close #52
=> Fix freezing on seek to end of audio

README.md
=> Add documentation for supported file types

Source/Model/Downloading/FileStorage.swift
Co-Authored-By: @fayinsky
close #58
=> Fix locating files in downloads

Source/Engine/Parser/AudioParser.swift, Source/Engine/Parser/AudioParserPacketListener.swift
=> fix crash on uncompressed audio with packet parsing

Example/SwiftAudioPlayer/ViewController.swift, Source/SAPlayer.swift, Source/SAPlayerFeatures.swift
=> add rate as a core property of SAPlayer

Source/SAPlayerFeatures.swift
=> Add minor documentation to skip silences feature

Source/Engine/AudioStreamEngine.swift, Source/Engine/Converter/AudioConverter.swift, Source/Engine/Converter/AudioConverterListener.swift
=> Fix PCM memory leak

Example/SwiftAudioPlayer/Base.lproj/Main.storyboard, Example/SwiftAudioPlayer/Model.swift
=> Update example app to include a radio stream link

Source/Engine/AudioEngine.swift, Source/Engine/AudioStreamEngine.swift
@niczyja should be fixed with this PR!
close #90
=> fix recursive polling logic

Example/Pods/Pods.xcodeproj/project.pbxproj, Example/SwiftAudioPlayer/ViewController.swift, README.md, Source/Directors/StreamingDownloadDirector.swift, Source/Engine/AudioEngine.swift, Source/Engine/AudioStreamEngine.swift, Source/Engine/AudioThrottler.swift, Source/Engine/Converter/AudioConverter.swift, Source/Engine/Parser/AudioParser.swift, Source/SAPlayer.swift, Source/SAPlayerDelegate.swift, Source/SAPlayerFeatures.swift, Source/SAPlayerPresenter.swift
=> Fix radio streaming playback to be smooth

Source/SAPlayer.swift, Source/SAPlayerDelegate.swift, Source/SAPlayerPresenter.swift
=> Fix bug introduced by queuing for lockscreen info

Example/SwiftAudioPlayer/ViewController.swift, Source/SAPlayer.swift, Source/SAPlayerFeatures.swift
=> fix maintaining rate changes while skip silences is enabled

Source/SAPlayer.swift
This fixes: https://github.com/tanhakabir/SwiftAudioPlayer/issues/117. Please review @tanhakabir .
=> fix: prevent mediainfo not being available yet in callbacks

Source/LockScreenViewProtocol.swift, Source/SALockScreenInfo.swift
- Add albumTitle for SALockScreenInfo
- Support disable skip forward/backward command
=> Improve LockScreen Info

Source/Engine/AudioEngine.swift, Source/Engine/AudioStreamEngine.swift
case 1:
```
"required condition is false: nil == owningEngine || GetEngine() == owningEngine"
```
case 2:
```
"required condition is false: _engine->IsRunning()"
```
=> Fix some "required condition is false" cases.

Source/Model/AudioDataManager.swift, Source/Model/Downloading/FileStorage.swift, Source/SAPlayerDownloader.swift
=> Experimental set download location
